### ISSUE TITLE
Object spread syntax causes error

### ISSUE THREAD

**Issue by zbjornson** [primitybio/vue-toolchain#2]
Babylon croaks on stuff like `const foo = {...bar}`.

**Comment by chearon** [comment]
That's cause it's still a proposal, I ran into this a while back too.

I'm playing around with Babel 7 and it looks like I can opt-in to parsing spread syntax, and the generator seems to work with that AST by default. Change coming soon...

**Comment by zbjornson** [comment]
TIL. I assumed it was in the array literal and functional spread proposals (landed).

Does Babel down-convert it automatically? Looks like Safari and Edge don't support it yet.

**Comment by chearon** [comment]
My goal is for this to not do any transformations at all, just get the AST and add the Vue-compiled render functions to it. I think that's possible with function spread.

But

>  Looks like Safari and Edge don't support it yet.

Sounds like it would be pointless to not transform object spread. So maybe we shouldn't do this...

**Comment by zbjornson** [comment]
Agreed, I'd rather not transpile anything, so we can close this until it's supported everywhere.
